name: movies
description: "A small movie-browser app that lets users browse movies, view details, and save favorites."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.9.0

flutter_intl:
  main_locale: en
  enabled: true

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  dio: ^5.9.0
  flutter_bloc: ^9.1.1
  json_annotation: ^4.9.0

  retrofit: ^4.7.2
  either_dart: ^1.0.0
  equatable: ^2.0.7
  envied: ^1.3.0
  cached_network_image: ^3.4.1
  get_it: ^8.2.0
  sembast: ^3.8.5+1
  path: ^1.9.1
  path_provider: ^2.1.5
  intl: ^0.20.2
  flutter_localizations:
    sdk: flutter
  shared_preferences: ^2.5.3
  flutter_native_splash: ^2.4.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.7.1
  envied_generator: ^1.3.0
  retrofit_generator: ^10.0.5
  json_serializable: ^6.11.1
  loggy: ^2.0.3
  mocktail: ^1.0.4

flutter_native_splash:
  image: "assets/images/popcorn.jpeg"
  color: "#FFFFFF"
  color_dark: "#121212"

flutter:
  uses-material-design: true
